### PR TITLE
Fixed publishing and archive not starting by force reinstalling dependencies

### PR DESCRIPTION
**Pull request by m1yag1**
Publishing and archive would not start after deployment. There seems to
be an issue with pip installing cnx-common as a dependency. This is a
stop gap solution that will be ultimately fixed by more maintenance work (https://github.com/openstax/cnx/issues/572) that
will resolve this entirely.

### CODE REVIEW

**Comment by scb6** [comment]
What is the ETA on the replacement fix? This fix seems like a sledgehammer that could increase deployment time on production deployment days.

**Comment by scb6** [comment]
if it is a one off fix for QA, then I think we should deploy from the branch and then delete the branch. If we merge this to master, then it will get pushed out to prod.

**Comment by m1yag1** [comment]
I'm fine w/ that approach. I can set the title to DO NOT MERGE.

**Comment by m1yag1** [comment]
@scb6 these are only the deps in the `environments/__prod_envs/files/ *` directory for publishing, and archive.

**publishing deps** total 63

```
amqp==2.5.0
appdirs==1.4.3
Beaker==1.10.1
billiard==3.6.0.0
celery==4.3.0
certifi==2019.6.16
chardet==3.0.4
cnx-archive==4.13.0
cnx-common==1.1.0
cnx-db==3.3.0
cnx-easybake==1.2.5
cnx-epub==0.18.0
cnx-publishing==0.17.0
cnx-query-grammar==0.2.2
cnx-recipes==1.35.0
cnx-transforms==1.2.0
cssselect==1.0.3
cnx-cssselect2==0.2.3
db-migrator==1.1.0
funcsigs==1.0.2
hupper==1.8.1
idna==2.8
Jinja2==2.10.1
kombu==4.6.3
lxml==4.3.4
MarkupSafe==1.1.1
openstax-accounts==1.0.0
packaging==19.0
parsimonious==0.8.1
Paste==3.0.8
PasteDeploy==2.0.1
PasteScript==3.1.0
pkg-resources==0.0.0
plaster==1.0
plaster-pastedeploy==0.7
psycopg2==2.8.3
PyICU==2.3.1
pyparsing==2.4.0
pyramid==1.10.4
pyramid-jinja2==2.8
pyramid-multiauth==0.9.0
pyramid-sawing==1.1.3
pyramid-translogger==0.1
python-memcached==1.59
pytz==2019.1
PyYAML==5.1.1
repoze.lru==0.7
requests==2.22.0
rhaptos.cnxmlutils==1.6.2
sanction==0.4.1
six==1.12.0
SQLAlchemy==1.3.5
tinycss2==0.6.1
translationstring==1.3
tzlocal==1.5.1
urllib3==1.25.3
venusian==1.2.0
vine==1.3.0
waitress==1.3.0
webencodings==0.5.1
WebOb==1.8.5
zope.deprecation==4.4.0
zope.interface==4.6.0
```

**Archive Deps** total 50

```
appdirs==1.4.3
Beaker==1.10.1
certifi==2019.6.16
chardet==3.0.4
cnx-archive==4.13.0
cnx-common==1.1.0
cnx-db==3.3.0
cnx-epub==0.18.0
cnx-query-grammar==0.2.2
cnx-transforms==1.2.0
db-migrator==1.1.0
funcsigs==1.0.2
hupper==1.8.1
idna==2.8
Jinja2==2.10.1
lxml==4.3.4
MarkupSafe==1.1.1
packaging==19.0
parsimonious==0.8.1
Paste==3.0.8
PasteDeploy==2.0.1
PasteScript==3.1.0
pkg-resources==0.0.0
plaster==1.0
plaster-pastedeploy==0.7
psycopg2==2.8.3
pyparsing==2.4.0
pyramid==1.10.4
pyramid-jinja2==2.8
pyramid-multiauth==0.9.0
pyramid-sawing==1.1.3
pyramid-translogger==0.1
python-memcached==1.59
pytz==2019.1
PyYAML==5.1.1
repoze.lru==0.7
requests==2.22.0
rhaptos.cnxmlutils==1.6.2
sanction==0.4.1
six==1.12.0
SQLAlchemy==1.3.5
translationstring==1.3
tzlocal==1.5.1
urllib3==1.25.3
venusian==1.2.0
waitress==1.3.0
webencodings==0.5.1
WebOb==1.8.5
zope.deprecation==4.4.0
zope.interface==4.6.0
```

Profiled results w/o forcereinstall:

```
Wednesday 24 July 2019  15:10:57 -0500 (0:00:00.043)       0:09:29.319 ******** 
=============================================================================== 
zope_common : run buildout ------------------------------------------------------------------------------------------- 131.51s
publishing_common : install publishing -------------------------------------------------------------------------------- 14.50s
publishing_common : install publishing -------------------------------------------------------------------------------- 14.29s
webview : download and unpack webview --------------------------------------------------------------------------------- 13.58s
rsyslog : install rsyslog and rsyslog-gnutls -------------------------------------------------------------------------- 12.82s
dtd_files : update apt cache ------------------------------------------------------------------------------------------ 12.80s
publishing_common : install publishing -------------------------------------------------------------------------------- 12.39s
check whether rhaptos site exists ------------------------------------------------------------------------------------- 10.14s
dtd_files : update apt cache ------------------------------------------------------------------------------------------- 9.27s
rsyslog : install rsyslog and rsyslog-gnutls --------------------------------------------------------------------------- 9.21s
cnx_database : install archive ----------------------------------------------------------------------------------------- 8.27s
rsyslog : install rsyslog and rsyslog-gnutls --------------------------------------------------------------------------- 7.73s
archive : install archive ---------------------------------------------------------------------------------------------- 7.38s
rsyslog : install rsyslog and rsyslog-gnutls --------------------------------------------------------------------------- 6.79s
rsyslog : install rsyslog and rsyslog-gnutls --------------------------------------------------------------------------- 6.79s
press_common : install latest dependencies ----------------------------------------------------------------------------- 6.57s
set up rhaptos print host ---------------------------------------------------------------------------------------------- 6.12s
set up collections allowed content types ------------------------------------------------------------------------------- 6.10s
press_common : install latest dependencies ----------------------------------------------------------------------------- 6.09s
shell ------------------------------------------------------------------------------------------------------------------ 6.08s

**Pull request closed without merging**
