### PR TITLE
Update rex redirects for __dev_envs

### PR DESCRIPTION
**Pull request by karenc**
-astronomy
+astronomy
-astronomy
+astronomy

### CODE REVIEW

**Comment by karenc** [comment]
@helenemccarron No, katalyst01 has rex redirects disabled: 

https://github.com/openstax/cnx-deploy/blob/master/environments/katalyst01/group_vars/all/vars.yml#L72

I guess we can remove the file from `environments/katalyst01`

In any case, we shouldn't merge this PR because the page slug has changed on staging but it doesn't look right for production.

**Comment by helenemccarron** [comment]
Ok, thank you for the clarification. From a recipes perspective, at this point, we are requesting that Katalyst01 and easyvm5 do *not* redirect so we can continue functional testing on webview. cc @openstaxalina

**Comment by karenc** [comment]
@helenemccarron No, this PR doesn't touch that variable so katalyst01 still doesn't redirect to rex.

**Comment by karenc** [comment]
Ok great!  I've changed the concourse pipeline to use prod archive instead of staging archive and now there are no changes :tada:

**Pull request closed without merging**
