### PR TITLE
Prevent caching response for google redirect

### PR DESCRIPTION
**Pull request by BryanEliDimas**
## Description
During testing of feature (https://github.com/openstax/cnx/issues/209), a bug was discovered: the response is cached for 60 seconds and during those 60 seconds, any subsequent requests to the same URL are not redirected as they should.

See this PR's comments for more background information: https://github.com/openstax/cnx-automation/pull/559

Or, before this change: https://github.com/openstax/cnx-automation/pull/559#issuecomment-478166340

And after this change: https://github.com/openstax/cnx-automation/pull/559#issuecomment-478721282

### CODE REVIEW

**Comment by karenc** [comment]
@BryanEliDimas I tested this locally and it doesn't seem to work for me.  It could be that my local set up is not quite right, could you run this test on dev (or wherever you have this deployed) and let me know how it is?

Start the python3 interpreter and import requests:

```
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
```

First, fetch a valid archive url (change `archive.local.cnx.org`) with the referer set to google.  We're expecting `'X-Varnish-Status': 'uncacheable - redirected google'` in the response header.

```
>>> requests.get('https://archive.local.cnx.org/contents/yqV9q0HH@18.1:yqV9q0HH@18.1', headers={'Referer': 'https://google.com/'}).headers
... 'X-Varnish-Status': 'uncacheable - redirected google' ...
```

Then fetch the same url without the referer.  We're expecting `'X-Varnish-Status': 'cacheable - Cache-Control in backend response'` in the response header.

```
>>> requests.get('https://archive.local.cnx.org/contents/yqV9q0HH@18.1:yqV9q0HH@18.1').headers
... X-Varnish-Status': 'cacheable - Cache-Control in backend response' ...
```

Then fetch the same url with the referer set to google again (same as the first one).  We're expecting `'X-Varnish-Status': 'uncacheable - redirected google'` in the response header.

```
>>> requests.get('https://archive.local.cnx.org/contents/yqV9q0HH@18.1:yqV9q0HH@18.1', headers={'Referer': 'https://google.com/'}).headers
```

When I tested locally, the third one returns `'X-Varnish-Status': 'cacheable - Cache-Control in backend response'` so it's not correct.

If you just let me know what you get from the dev server and it returns the right results, I'll approve and merge the PR.

**Comment by BryanEliDimas** [comment]
@karenc Yes, I've tested it in the dev server and I posted my results here: https://github.com/openstax/cnx-automation/pull/559#issuecomment-478721282

**Comment by karenc** [comment]
@BryanEliDimas I tried the above tests on dev.cnx.org and it's not passing:

```
karen@yachiyo:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://archive-dev.cnx.org/contents/ab0fde1e-feb3-4d64-a60c-ae36e67440cf@8', headers={'Referer': 'https://google.com/'}).headers.get('X-Varnish-Status')
'uncacheable - redirected google'
```

^ This is good

```
>>> requests.get('https://archive-dev.cnx.org/contents/ab0fde1e-feb3-4d64-a60c-ae36e67440cf@8').headers.get('X-Varnish-Status')
'cacheable - Cache-Control in backend response'
```

^ This is expected as well

```
>>> requests.get('https://archive-dev.cnx.org/contents/ab0fde1e-feb3-4d64-a60c-ae36e67440cf@8', headers={'Referer': 'https://google.com/'}).headers.get('X-Varnish-Status')
'cacheable - Cache-Control in backend response'
```

^ This should have the same results as the first request `'uncacheable - redirected google'` but it doesn't.

**Comment by BryanEliDimas** [comment]
@karenc Ok, I've pushed a commit with the fix. These are the varnish logs (I believe both req/resp are exactly the same):

```
bryaneli@dev00:~$ sudo /usr/bin/varnishlog -n varnish -q "ReqURL ~ 'contents'"
*   << Request  >> 5         
-   Begin          req 4 rxreq
-   Timestamp      Start: 1554750959.428385 0.000000 0.000000
-   Timestamp      Req: 1554750959.428385 0.000000 0.000000
-   ReqStart       128.42.169.74 40224
-   ReqMethod      GET
-   ReqURL         /contents/ab0fde1e-feb3-4d64-a60c-ae36e67440cf@8
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: archive-dev.cnx.org
-   ReqHeader      User-Agent: curl/7.54.0
-   ReqHeader      Accept: */*
-   ReqHeader      Referer: https://google.com/
-   ReqHeader      X-Secure: true
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-For: 10.213.176.9
-   ReqHeader      Connection: close
-   ReqUnset       X-Forwarded-For: 10.213.176.9
-   ReqHeader      X-Forwarded-For: 10.213.176.9, 128.42.169.74
-   VCL_call       RECV
-   VCL_acl        NO_MATCH block
-   VCL_return     pass
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       PASS
-   VCL_return     fetch
-   Link           bereq 6 pass
-   Timestamp      Fetch: 1554750959.542789 0.114404 0.114404
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Access-Control-Allow-Headers: origin,dnt,accept-encoding,accept-language,keep-alive,user-agent,x-requested-with,if-modified-since,cache-control,content-type
-   RespHeader     Access-Control-Allow-Methods: GET, OPTIONS
-   RespHeader     Access-Control-Allow-Origin: *
-   RespHeader     Cache-Control: max-age=31536000, public
-   RespHeader     Content-Length: 83656
-   RespHeader     Content-Type: application/json
-   RespHeader     Date: Mon, 08 Apr 2019 19:15:59 GMT
-   RespHeader     Etag: "mk7ZqA0Zgzl/0HsxioVS9A"
-   RespHeader     Expires: Tue, 07 Apr 2020 19:15:59 GMT
-   RespHeader     Link: <https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood> ;rel="Canonical"
-   RespHeader     Server: waitress
-   RespHeader     status: 302
-   RespHeader     Location: https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood
-   RespHeader     X-Varnish-Status: uncacheable - redirected google
-   RespHeader     X-Varnish-Canonical-Url: https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood
-   RespHeader     X-Varnish-Backend: dev00_archive0
-   RespHeader     X-Varnish-Ttl: 0.000
-   RespHeader     X-Varnish: 5
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Varnish-Cache: MISS
-   VCL_return     deliver
-   Timestamp      Process: 1554750959.542813 0.114428 0.000024
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: close
-   Timestamp      Resp: 1554750959.545973 0.117589 0.003161
-   ReqAcct        252 0 252 1109 83656 84765
-   End            

*   << Request  >> 32770     
-   Begin          req 32769 rxreq
-   Timestamp      Start: 1554750964.555618 0.000000 0.000000
-   Timestamp      Req: 1554750964.555618 0.000000 0.000000
-   ReqStart       128.42.169.74 40246
-   ReqMethod      GET
-   ReqURL         /contents/ab0fde1e-feb3-4d64-a60c-ae36e67440cf@8
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: archive-dev.cnx.org
-   ReqHeader      User-Agent: curl/7.54.0
-   ReqHeader      Accept: */*
-   ReqHeader      Referer: https://google.com/
-   ReqHeader      X-Secure: true
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-For: 10.213.176.9
-   ReqHeader      Connection: close
-   ReqUnset       X-Forwarded-For: 10.213.176.9
-   ReqHeader      X-Forwarded-For: 10.213.176.9, 128.42.169.74
-   VCL_call       RECV
-   VCL_acl        NO_MATCH block
-   VCL_return     pass
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       PASS
-   VCL_return     fetch
-   Link           bereq 32771 pass
-   Timestamp      Fetch: 1554750964.672948 0.117330 0.117330
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Access-Control-Allow-Headers: origin,dnt,accept-encoding,accept-language,keep-alive,user-agent,x-requested-with,if-modified-since,cache-control,content-type
-   RespHeader     Access-Control-Allow-Methods: GET, OPTIONS
-   RespHeader     Access-Control-Allow-Origin: *
-   RespHeader     Cache-Control: max-age=31536000, public
-   RespHeader     Content-Length: 83656
-   RespHeader     Content-Type: application/json
-   RespHeader     Date: Mon, 08 Apr 2019 19:16:04 GMT
-   RespHeader     Etag: "mk7ZqA0Zgzl/0HsxioVS9A"
-   RespHeader     Expires: Tue, 07 Apr 2020 19:16:04 GMT
-   RespHeader     Link: <https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood> ;rel="Canonical"
-   RespHeader     Server: waitress
-   RespHeader     status: 302
-   RespHeader     Location: https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood
-   RespHeader     X-Varnish-Status: uncacheable - redirected google
-   RespHeader     X-Varnish-Canonical-Url: https://dev.cnx.org/contents/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c:ab0fde1e-feb3-4d64-a60c-ae36e67440cf/Likelihood
-   RespHeader     X-Varnish-Backend: dev00_archive0
-   RespHeader     X-Varnish-Ttl: 0.000
-   RespHeader     X-Varnish: 32770
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Varnish-Cache: MISS
-   VCL_return     deliver
-   Timestamp      Process: 1554750964.672979 0.117362 0.000031
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: close
-   Timestamp      Resp: 1554750964.673191 0.117573 0.000212
-   ReqAcct        252 0 252 1113 83656 84769
-   End            
```

**Pull request merged**
