### PR TITLE
Lint check all changes using Travis-CI

### PR DESCRIPTION
**Pull request by pumazi**
This adds `ansible-lint` for linting this project. It fails horrendously right now, but it's a conversation starter none the less. 🥂

### CODE REVIEW

**Comment by scb6** [comment]
I am on board with adding a linter to start the conversation about getting `cnx-deploy` updated. We can prioritize these issues as they come. I am a little concerned this will create a lot on noise while issues are being created, but as long as this doesn't break the deployment while things are being fixed, I approve.

**Comment by pumazi** [comment]
Sounds like we'll need to get the initial linting completed before we can push this in then. That's tedious task that we'll have to find time to get done.

**Comment by m1yag1** [comment]
Change this into using a pre-commit hook.

**Comment by Bkblodget** [comment]
as a developer i would like to use pre-comit to lint my newly staged changes for cnx-deploy

**Pull request closed without merging**
